### ISSUE TITLE
Kogitoinfra does not support the new keycloak operator deployments

### ISSUE THREAD

**Issue by jorgelon** [kiegroup/kogito-operator#20]
### Describe the bug

Why I try to declare a Kogitoinfra with "kind: Keycloak" using a keycloak operator deployment, the controller gives me an error telling me k8s.keycloak.org/v2alpha1 api is not supported
Only keycloak.org/v1alpha1 api is  supported

I think that api is for resources deployed with the old keycloak operator

Kubernetes 1.29 in eks

### Actual behavior

      message: >-
        API k8s.keycloak.org/v2alpha1 is not supported for kind Keycloak.
        Supported APIs are: [infinispan.infinispan.org/v1
        kafka.kafka.strimzi.io/v1beta2 keycloak.keycloak.org/v1alpha1
        broker.eventing.knative.dev/v1 mongodb.mongodbcommunity.mongodb.com/v1]
      reason: UnsupportedAPIKind
      status: 'False'
      type: Configured

### How to Reproduce?

```
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoSupportingService
metadata:
  name: management-console
spec:
  serviceType: MgmtConsole
  image: quay.io/kiegroup/kogito-management-console:1.44
  infra:
    - keycloak-kogito
```

---
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-kogito
spec:
```
...

### Kogito Operator version or git rev

8.0.4.GA, main and 1.44.1
